apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-external-secrets
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: redirecterr-config
    template:
      data:
        config.yaml: |
          overseerr_url: "https://jellyseerr.hknlab.io/"
          overseerr_api_token: "{{ .api_token }}"

          approve_on_no_match: True

          instances:
            radarr: # Custom instance name
              server_id: 0
              root_folder: "/media/Movies"
            sonarr: # Custom instance name
              server_id: 0
              root_folder: "/media/Television"

          filters:
            - media_type: movie
              apply:
                - radarr
            - media_type: tv
              apply: sonarr

  data:
    - secretKey: api_token
      remoteRef:
        key: apps/overseerr
        property: api_token
