kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: helm-tdarr-scc
  namespace: tdarr
subjects:
  - kind: ServiceAccount
    name: default
    namespace: tdarr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'
