apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matrix-redis-external-secrets
  namespace: matrix-synapse
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: redis
  data:
    - secretKey: redis-password
      remoteRef:
        key: apps/matrix-synapse
        property: redis-password
