apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netdata
  namespace: openshift-gitops
spec:
  project: default

  syncPolicy:
    automated:
      prune: false
    syncOptions:
      - CreateNamespace=true

  destination:
    server: https://kubernetes.default.svc
    namespace: netdata

  sources:
  - repoURL: https://netdata.github.io/helmchart/
    chart: netdata
    targetRevision: 3.7.127
    helm:
      releaseName: netdata
      valueFiles:
        - $values/gitops/helm/netdata/values.yaml

  - repoURL: https://gitlab.developer.hkn.lab/infrastructure-as-code/openshift4/clusters/hub.git
    targetRevision: HEAD
    ref: values

  - repoURL: https://gitlab.developer.hkn.lab/infrastructure-as-code/openshift4/clusters/hub.git
    targetRevision: HEAD
    path: gitops/helm/netdata/extras
