apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matrix-synapse
  namespace: openshift-gitops
spec:
  project: default

  syncPolicy:
    automated:
      prune: false
    syncOptions:
    - CreateNamespace=true

  destination:
    server: https://kubernetes.default.svc
    namespace: matrix-synapse

  sources:
  - repoURL: https://gitlab.com/ananace/charts.git
    targetRevision: HEAD
    path: charts/matrix-synapse
    helm:
      releaseName: matrix-synapse
      valueFiles:
        - $values/gitops/helm/matrix-synapse/values.yaml

  - repoURL: https://gitlab.developer.hkn.lab/infrastructure-as-code/openshift4/clusters/hub.git
    targetRevision: HEAD
    ref: values

  - repoURL: https://gitlab.developer.hkn.lab/infrastructure-as-code/openshift4/clusters/hub.git
    targetRevision: HEAD
    path: gitops/helm/matrix-synapse/extras

  ignoreDifferences:
    - group: Batch
      kind: Job
