replicaCount: 1

image:
  repository: thijsvanloef/palworld-server-docker
  pullPolicy: IfNotPresent
  tag: "latest"

# server:
#   password: 'CHANGEME'
#   adminPassword: 'CHANGEME'

env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: PORT
    value: '8211' # Optional but recommended
  - name: PLAYERS
    value: '16' # Optional but recommended
  - name: MULTITHREADING
    value: 'true'
  - name: RCON_ENABLED
    value: 'true'
  - name: RCON_PORT
    value: '25575'
  - name: TZ
    value: "UTC"
  - name: COMMUNITY
    value: 'true'  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
  - name: SERVER_NAME
    value: "[HyperKineticNerd] Palworld"
  - name: SERVER_DESCRIPTION
    value: "palworld-server-docker by Thijs van Loef"
  - name: ALLOW_CONNECT_PLATFORM
    value: "Steam"

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: "default"

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 1000
  # seccompProfile:
  #   type: RuntimeDefault
  # capabilities:
  #   drop: ["ALL"]

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: true
  runAsNonRoot: true

service:
  type: NodePort
  game:
    port: 8211
    nodePort: 8211
  query:
    port: 27015
    nodePort: 27015
  api:
    port: 8212
    nodePort: 8212

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    memory: "32Gi"
    cpu: "6000m"
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes:
  - name: data
    persistentVolumeClaim:
      claimName: pvc-palworld
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: data
    mountPath: /palworld/

nodeSelector: {}

tolerations: []

affinity: {}
