apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: openshift-gitops
spec:
  project: default

  syncPolicy:
    automated:
      prune: false
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true

  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns

  sources:
  - repoURL: https://charts.hknlab.io
    chart: external-dns
    targetRevision: 0.1.1
    helm:
      releaseName: cloudflare
      valueFiles:
        - $values/gitops/helm/external-dns/values.yaml

  - repoURL: https://gitlab.developer.hkn.lab/infrastructure-as-code/openshift4/clusters/hub.git
    targetRevision: HEAD
    ref: values

  # - repoURL: https://gitlab.developer.hkn.lab/infrastructure-as-code/openshift4/clusters/hub.git
  #   targetRevision: HEAD
  #   path: gitops/helm/external-dns/extras
