apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashicorp-vault
  namespace: openshift-gitops
spec:
  project: default

  syncPolicy:
    automated:
      prune: false
    syncOptions:
    - CreateNamespace=true

  ignoreDifferences:
  - group: "admissionregistration.k8s.io"
    kind: "MutatingWebhookConfiguration"
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  sources:
  - repoURL: https://helm.releases.hashicorp.com
    chart: vault  # Set this when pulling directly from a Helm repo. DO NOT set for git-hosted Helm charts.
    targetRevision: 0.29.1  # For Helm, this refers to the chart version.
    helm:
      releaseName: vault
      valueFiles:
        - $values/gitops/helm/hashicorp-vault/values.yaml

  - repoURL: https://gitlab.developer.hkn.lab/infrastructure-as-code/openshift4/clusters/hub.git
    targetRevision: HEAD
    ref: values
