apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: openshift-gitops
  annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  project: default

  syncPolicy:
    automated:
      prune: false
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - SkipDryRunOnMissingResource=true

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  sources:
  - repoURL: https://charts.jetstack.io # oci://quay.io/jetstack/charts/cert-manager
    # path: .
    chart: cert-manager
    targetRevision: v1.18.2
    helm:
      releaseName: cert-manager
      valuesObject:
        crds:
          enabled: true

  - repoURL: https://gitlab.developer.hkn.lab/infrastructure-as-code/openshift4/clusters/hub.git
    targetRevision: HEAD
    path: gitops/helm/cert-manager/extras

