kind: KeycloakRealmImport
apiVersion: k8s.keycloak.org/v2alpha1
metadata:
  name: keycloak-canada-ldap-realm-import
  labels:
    app: sso
  namespace: keycloak
spec:
  keycloakCRName: keycloak
  realm:
    id: ca
    realm: ca
    displayName: CA Realm
    userFederationProviders:
      - displayName: FreeIPA
        providerName: FreeIPA
        config:
          vendor: ad
          connectionUrl: ldap://ipa2.hkn.lab
          bindType: simple
          bindDn: uid=ldap-sa,cn=users,cn=accounts,dc=hkn,dc=lab
          bindCredentials: 'CHANGEME'
          usersDn: cn=users,cn=accounts,dc=hkn,dc=lab
          usernameLDAPAttribute: uid
          uuidLDAPAttribute: entryUUID
          searchScope: "2" # sub
          useTruststoreSpi: ldapsOnly
          userObjectClasses: inetOrgPerson, organizationalPerson
          rdnLDAPAttribute: uid
          editMode: WRITABLE
