---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-webui-external-secrets
  namespace: netbox
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: netbox-webui-secrets
  dataFrom:
    - extract:
        key: apps/netbox/webui
        # property: .

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-postgresql-external-secrets
  namespace: netbox
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: netbox-postgres-secrets
  dataFrom:
    - extract:
        key: apps/netbox/postgresql
        # property: .

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-redis-external-secrets
  namespace: netbox
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: netbox-redis-secrets
  dataFrom:
    - extract:
        key: apps/netbox/redis
        # property: .

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-valkey-external-secrets
  namespace: netbox
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: netbox-valkey
  dataFrom:
    - extract:
        key: apps/netbox/valkey
        # property: .
