apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: openshift-gitops
spec:
  project: default

  syncPolicy:
    automated:
      prune: false
    syncOptions:
    - CreateNamespace=true

  destination:
    server: https://kubernetes.default.svc
    namespace: immich

  sources:
  - repoURL: https://immich-app.github.io/immich-charts
    chart: immich
    targetRevision: 0.9.3
    helm:
      releaseName: immich
      valueFiles:
        - $values/gitops/helm/immich/values.yaml

  - repoURL: https://gitlab.developer.hkn.lab/infrastructure-as-code/openshift4/clusters/hub.git
    targetRevision: HEAD
    ref: values
