apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyseerr
  namespace: openshift-gitops
spec:
  project: default

  syncPolicy:
    automated:
      prune: false
    syncOptions:
    - CreateNamespace=true

  destination:
    server: https://kubernetes.default.svc
    namespace: jellyseerr

  sources:
  - repoURL: https://charts.hknlab.io
    chart: jellyseerr
    targetRevision: 0.1.1
    helm:
      releaseName: jellyseerr
      valueFiles:
        - $values/gitops/helm/jellyseerr/values.yaml

  - repoURL: https://gitlab.developer.hkn.lab/infrastructure-as-code/openshift4/clusters/hub.git
    targetRevision: HEAD
    ref: values

  - repoURL: https://gitlab.developer.hkn.lab/infrastructure-as-code/openshift4/clusters/hub.git
    targetRevision: HEAD
    path: gitops/helm/jellyseerr/extras
