apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhbk
  namespace: openshift-gitops
spec:
  project: default

  syncPolicy:
    automated:
      prune: false
    syncOptions:
    - CreateNamespace=true

  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak

  sources:
  - repoURL: https://charts.hknlab.io
    chart: rhbk
    targetRevision: 0.1.0
    helm:
      releaseName: keycloak
      valueFiles:
        - $values/gitops/helm/rhbk/values.yaml

  - repoURL: https://gitlab.developer.hkn.lab/infrastructure-as-code/openshift4/clusters/hub.git
    targetRevision: HEAD
    ref: values

  - repoURL: https://gitlab.developer.hkn.lab/infrastructure-as-code/openshift4/clusters/hub.git
    targetRevision: HEAD
    path: gitops/helm/rhbk/extras
