apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-external-secrets
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: cloudflare-api-token-secret
  data:
    - secretKey: api-token
      remoteRef:
        key: cluste/hub/cert-manager/cloudflare
        property: api-token
