# Default values for cert-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

operator:
  config:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/hook: Skip
      argocd.argoproj.io/sync-options: Prune=false

issuer:
  cluster: true
  acmeServer: "https://acme-v02.api.letsencrypt.org/directory"
  email: "sean.nelson.04@gmail.com"
  preferredChain: ""
  privateKeySecretRef: letsencrypt-account-key
  solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
