apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matrix-redis
  namespace: openshift-gitops
spec:
  project: default

  syncPolicy:
    automated:
      prune: false
    syncOptions:
    - CreateNamespace=true

  destination:
    server: https://kubernetes.default.svc
    namespace: matrix-synapse

  sources:
  - repoURL: registry-1.docker.io/bitnamicharts
    chart: redis
    targetRevision: 20.11.3
    helm:
      releaseName: redis
      valueFiles:
        - $values/gitops/helm/matrix-redis/values.yaml

  - repoURL: https://gitlab.developer.hkn.lab/infrastructure-as-code/openshift4/clusters/hub.git
    targetRevision: HEAD
    ref: values
