---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-home-assistant-config
  labels:
    fstype: nfs
    app: home-assistant
spec:
  capacity:
    storage: 30Ti
  accessModes:
  - ReadWriteMany
  nfs:
    path: /volume1/docker/volumes/home-assistant
    server: 172.16.100.10
  persistentVolumeReclaimPolicy: Retain
