---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-homebridge-config
  labels:
    fstype: nfs
    app: homebridge
spec:
  capacity:
    storage: 30Ti
  accessModes:
  - ReadWriteMany
  nfs:
    path: /volume1/docker/volumes/homebridge
    server: 172.16.100.10
  persistentVolumeReclaimPolicy: Retain
