---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-qbittorrent-config
  labels:
    fstype: nfs
    app: qbittorrent
spec:
  capacity:
    storage: 30Ti
  accessModes:
  - ReadWriteMany
  nfs:
    path: /volume1/docker/volumes/qbittorrent
    server: 172.16.100.10
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-qbittorrent-downloads
  labels:
    fstype: nfs
    app: qbittorrent
spec:
  capacity:
    storage: 30Ti
  accessModes:
  - ReadWriteMany
  nfs:
    path: /volume1/downloads
    server: 172.16.100.10
  persistentVolumeReclaimPolicy: Retain
