---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-sabnzbd-config
  labels:
    fstype: nfs
    app: sabnzbd
spec:
  capacity:
    storage: 30Ti
  accessModes:
  - ReadWriteMany
  nfs:
    path: /volume1/docker/volumes/sabnzbd
    server: 172.16.100.10
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-sabnzbd-downloads
  labels:
    fstype: nfs
spec:
  capacity:
    storage: 30Ti
  accessModes:
  - ReadWriteMany
  nfs:
    path: /volume1/downloads/completed
    server: 172.16.100.10
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-sabnzbd-incomplete
  labels:
    fstype: nfs
spec:
  capacity:
    storage: 30Ti
  accessModes:
  - ReadWriteMany
  nfs:
    path: /volume1/downloads/incomplete
    server: 172.16.100.10
  persistentVolumeReclaimPolicy: Retain
