global:
  storageClass: "basic"

auth:
  existingSecret: "netbox-valkey"
  existingSecretPasswordKey: "valkey-password"

master:
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false

replica:
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
