# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: bitwarden-sa
#   namespace: bitwarden

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bitwarden-scc-anyuid
  namespace: bitwarden
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: bitwarden-sa
  namespace: bitwarden
