apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: openshift-gitops
spec:
  project: default

  syncPolicy:
    automated:
      prune: false
    syncOptions:
    - CreateNamespace=true

  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin

  sources:
  - repoURL: https://charts.hknlab.io
    chart: jellyfin
    targetRevision: 0.1.6
    helm:
      releaseName: jellyfin
      valueFiles:
        - $values/gitops/helm/jellyfin/values.yaml

  - repoURL: https://gitlab.developer.hkn.lab/infrastructure-as-code/openshift4/clusters/hub.git
    targetRevision: HEAD
    ref: values

  - repoURL: https://gitlab.developer.hkn.lab/infrastructure-as-code/openshift4/clusters/hub.git
    targetRevision: HEAD
    path: gitops/helm/jellyfin/extras
