apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: element-web
  namespace: openshift-gitops
spec:
  project: default

  syncPolicy:
    automated:
      prune: false
    syncOptions:
    - CreateNamespace=true

  destination:
    server: https://kubernetes.default.svc
    namespace: element-web

  sources:
  - repoURL: https://gitlab.com/ananace/charts.git
    path: charts/element-web
    targetRevision: HEAD

    helm:
      releaseName: element-web
      valueFiles:
        - $values/gitops/helm/element-web/values.yaml

  - repoURL: https://gitlab.developer.hkn.lab/infrastructure-as-code/openshift4/clusters/hub.git
    targetRevision: HEAD
    ref: values

  - repoURL: https://gitlab.developer.hkn.lab/infrastructure-as-code/openshift4/clusters/hub.git
    targetRevision: HEAD
    path: gitops/helm/element-web/extras

  ignoreDifferences:
    - group: Batch
      kind: Job
