apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-valkey-external-secrets
  namespace: netbox
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: netbox-valkey
  data:
    - secretKey: valkey-password
      remoteRef:
        key: apps/netbox/valkey
        property: valkey-password
