---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: basic
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: csi.trident.netapp.io
parameters:
  backendType: ontap-nas
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: Immediate

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: iscsi
  # annotations:
    # storageclass.kubernetes.io/is-default-class: 'true'
provisioner: csi.trident.netapp.io
parameters:
  backendType: ontap-san
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: Immediate
